name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup corepack
        run: |
          corepack enable
          corepack enable pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run formatter
        run: pnpm biome check .
      - name: Run linter
        run: pnpm lint
